services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synerx-backend
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env              # <-- fixed: look in current backend/ dir
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./.cache:/app/.cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

    # GPU (uncomment if host has NVIDIA runtime)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]
    # runtime: nvidia
