# RunPod deployment with volume mounting (no file upload needed)
# Usage: docker-compose -f docker-compose.volume.yml up

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synerx-backend-volume
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      # RunPod environment variables
      - SERVER_URL=${SERVER_URL:-http://localhost:8000}
      - PORT=8000
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:64
      
      # Database
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      
      # R2 Storage
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME:-synerx-videos}
      
    volumes:
      # Mount your local code directly (no upload needed!)
      - .:/app                           # Mount entire backend folder
      - ./models:/app/models:ro          # Read-only models
      - ./temp:/app/temp                 # R2 streaming temp files
      - ./output:/app/output             # Processed videos (temporary)
      - ./.cache:/app/.cache             # Model cache
      
    restart: unless-stopped
    
    # GPU configuration for RunPod
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    runtime: nvidia
    
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      
    # RunPod optimizations
    shm_size: 2gb  # Shared memory for video processing
    ulimits:
      memlock: -1
      stack: 67108864
