/*
  # Add job_id column to videos table
  
  1. Changes
    - Add `job_id` column (uuid) to videos table for tracking backend processing jobs
    - Add index on job_id for faster lookups
    - Make job_id unique to prevent duplicate job tracking
  
  2. Notes
    - job_id will be generated by the frontend and sent to backend
    - This links the video record with the processing job
*/

DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'videos' AND column_name = 'job_id'
  ) THEN
    ALTER TABLE videos ADD COLUMN job_id uuid UNIQUE;
    CREATE INDEX IF NOT EXISTS idx_videos_job_id ON videos(job_id);
  END IF;
END $$;
